import { DocTypeConfig } from "./types";
import { DPA_TEMPLATE } from "../templates/dpa";

export const dpaConfig: DocTypeConfig = {
  docTypeId: "dpa",
  catalogFilename: "DPA.md",
  displayName: "Data Processing Agreement",
  description: "Common Paper standard DPA for GDPR-compliant data processing relationships",
  isSupplementDoc: true,
  templateContent: DPA_TEMPLATE,
  coverPage: {
    partyALabel: "Provider",
    partyBLabel: "Customer",
    showSignatures: true,
  },
  fields: [
    {
      key: "parentAgreementName",
      label: "Parent Agreement",
      type: "text",
      hint: "name of the agreement this DPA supplements",
      placeholder: "Cloud Service Agreement dated January 1, 2026",
      templateMarker: "Agreement",
      coverPageOrder: 1,
    },
    {
      key: "categoriesOfPersonalData",
      label: "Categories of Personal Data",
      type: "textarea",
      placeholder: "Names, email addresses, usage data",
      templateMarker: "Categories of Personal Data",
      coverPageOrder: 2,
    },
    {
      key: "categoriesOfDataSubjects",
      label: "Categories of Data Subjects",
      type: "textarea",
      placeholder: "Employees, customers, end users of Customer",
      templateMarker: "Categories of Data Subjects",
      coverPageOrder: 3,
    },
    {
      key: "specialCategoryData",
      label: "Special Category Data",
      type: "textarea",
      hint: "GDPR Article 9 data — leave blank if none",
      placeholder: "None",
      templateMarker: "Special Category Data",
      coverPageOrder: 4,
    },
    {
      key: "approvedSubprocessors",
      label: "Approved Subprocessors",
      type: "textarea",
      placeholder: "AWS (US) — cloud hosting; Stripe (US) — payment processing",
      templateMarker: "Approved Subprocessors",
      coverPageOrder: 5,
    },
    {
      key: "governingMemberState",
      label: "Governing Member State",
      type: "text",
      hint: "EU member state governing the Standard Contractual Clauses",
      placeholder: "Ireland",
      templateMarker: "Governing Member State",
      coverPageOrder: 6,
    },
    {
      key: "securityPolicy",
      label: "Security Policy",
      type: "text",
      hint: "URL to Provider's security policy",
      placeholder: "https://provider.com/security",
      templateMarker: "Security Policy",
    },
    {
      key: "providerSecurityContact",
      label: "Provider Security Contact",
      type: "text",
      hint: "email for security audit requests",
      placeholder: "security@provider.com",
      templateMarker: "Provider Security Contact",
    },
  ],
};
