import { DocTypeConfig } from "./types";
import { PARTNERSHIP_TEMPLATE } from "../templates/partnership";

export const partnershipConfig: DocTypeConfig = {
  docTypeId: "partnership",
  catalogFilename: "Partnership-Agreement.md",
  displayName: "Partnership Agreement",
  description: "Common Paper standard agreement governing reseller and referral partnerships",
  isSupplementDoc: false,
  templateContent: PARTNERSHIP_TEMPLATE,
  coverPage: {
    partyALabel: "Company",
    partyBLabel: "Partner",
    showSignatures: true,
  },
  fields: [
    {
      key: "effectiveDate",
      label: "Effective Date",
      type: "date",
      templateMarker: "Effective Date",
      coverPageOrder: 1,
    },
    {
      key: "endDate",
      label: "End Date",
      type: "date",
      templateMarker: "End Date",
      coverPageOrder: 2,
    },
    {
      key: "territory",
      label: "Territory",
      type: "text",
      placeholder: "Worldwide",
      templateMarker: "Territory",
      coverPageOrder: 3,
    },
    {
      key: "obligations",
      label: "Obligations",
      type: "textarea",
      hint: "describe each party's obligations",
      placeholder: "Company: provide product access and training. Partner: refer customers and promote the product.",
      templateMarker: "Obligations",
      coverPageOrder: 4,
    },
    {
      key: "paymentProcess",
      label: "Payment Process",
      type: "textarea",
      hint: "how fees are paid between parties",
      placeholder: "Partner earns 20% commission on referred customer revenue, paid monthly",
      templateMarker: "Payment Process",
      coverPageOrder: 5,
    },
    {
      key: "governingLaw",
      label: "Governing Law",
      type: "text",
      hint: "US state name",
      placeholder: "Delaware",
      templateMarker: "Governing Law",
      coverPageOrder: 6,
    },
    {
      key: "chosenCourts",
      label: "Chosen Courts",
      type: "text",
      hint: "city/county and state",
      placeholder: "New Castle, Delaware",
      templateMarker: "Chosen Courts",
      coverPageOrder: 7,
    },
    {
      key: "generalCapAmount",
      label: "General Cap Amount",
      type: "text",
      placeholder: "Fees paid in the prior 12 months",
      templateMarker: "General Cap Amount",
    },
    {
      key: "brandGuidelines",
      label: "Brand Guidelines",
      type: "text",
      hint: "URL to brand usage guidelines",
      placeholder: "https://company.com/brand",
      templateMarker: "Brand Guidelines",
    },
    {
      key: "additionalWarranties",
      label: "Additional Warranties",
      type: "textarea",
      placeholder: "None",
      templateMarker: "Additional Warranties",
    },
  ],
};
