import { DocTypeConfig } from "./types";
import { PSA_TEMPLATE } from "../templates/psa";

export const psaConfig: DocTypeConfig = {
  docTypeId: "psa",
  catalogFilename: "psa.md",
  displayName: "Professional Services Agreement",
  description: "Common Paper standard agreement for professional and consulting services engagements",
  isSupplementDoc: false,
  templateContent: PSA_TEMPLATE,
  coverPage: {
    partyALabel: "Provider",
    partyBLabel: "Customer",
    showSignatures: true,
  },
  fields: [
    {
      key: "effectiveDate",
      label: "Effective Date",
      type: "date",
      templateMarker: "Effective Date",
      coverPageOrder: 1,
    },
    {
      key: "governingLaw",
      label: "Governing Law",
      type: "text",
      hint: "US state name",
      placeholder: "Delaware",
      templateMarker: "Governing Law",
      coverPageOrder: 2,
    },
    {
      key: "chosenCourts",
      label: "Chosen Courts",
      type: "text",
      hint: "city/county and state",
      placeholder: "New Castle, Delaware",
      templateMarker: "Chosen Courts",
      coverPageOrder: 3,
    },
    {
      key: "generalCapAmount",
      label: "General Cap Amount",
      type: "text",
      placeholder: "Fees paid in the prior 12 months",
      templateMarker: "General Cap Amount",
      coverPageOrder: 4,
    },
    {
      key: "increasedCapAmount",
      label: "Increased Cap Amount",
      type: "text",
      placeholder: "2x fees paid in the prior 12 months",
      templateMarker: "Increased Cap Amount",
    },
    {
      key: "increasedClaims",
      label: "Increased Claims",
      type: "textarea",
      placeholder: "IP infringement, gross negligence, willful misconduct",
      templateMarker: "Increased Claims",
    },
    {
      key: "unlimitedClaims",
      label: "Unlimited Claims",
      type: "textarea",
      placeholder: "Death or bodily injury, fraud",
      templateMarker: "Unlimited Claims",
    },
    {
      key: "providerCoveredClaims",
      label: "Provider Covered Claims",
      type: "textarea",
      placeholder: "Third-party IP infringement claims arising from the services",
      templateMarker: "Provider Covered Claims",
    },
    {
      key: "customerCoveredClaims",
      label: "Customer Covered Claims",
      type: "textarea",
      placeholder: "Third-party claims arising from Customer Materials",
      templateMarker: "Customer Covered Claims",
    },
    {
      key: "additionalWarranties",
      label: "Additional Warranties",
      type: "textarea",
      placeholder: "None",
      templateMarker: "Additional Warranties",
    },
    {
      key: "securityPolicy",
      label: "Security Policy",
      type: "text",
      hint: "URL or description",
      placeholder: "https://provider.com/security",
      templateMarker: "Security Policy",
    },
    {
      key: "customerPolicies",
      label: "Customer Policies",
      type: "text",
      hint: "policies Provider must comply with, if any",
      placeholder: "None",
      templateMarker: "Customer Policies",
    },
    {
      key: "insuranceMinimums",
      label: "Insurance Minimums",
      type: "textarea",
      placeholder: "Commercial general liability: $1M per occurrence",
      templateMarker: "Insurance Minimums",
    },
  ],
};
